### ISSUE TITLE
Ubuntu 20.04 also needs the ppa

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/ansible-repos#1]
Hi,
I tried to install slurm with the ansible role as in the GTN on ubuntu 20.04 and I add issues with slurm-drmaa. I just found that this playbook take care of this but unfortunately only for 18.04. I think you should extend the cases when you need the ppa:

https://github.com/galaxyproject/ansible-repos/blob/8bf4df36c7007d53f79650b8e63318566af2a4f0/tasks/main.yml#L6

Many thanks,

Lucille

**Comment by natefoo** [comment]
Fixed in #2, released as version 0.0.2 in galaxy.ansible.com.

**Comment by lldelisle** [comment]
Thanks
